"use client"

import React, { createContext, useContext, useState, ReactNode } from 'react'

type Language = 'en' | 'am'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en')

  const translations = {
    en: {
      // Header
      'header.home': 'Home',
      'header.about': 'About',
      'header.research': 'Research',
      'header.publications': 'Publications',
      'header.work': 'Work',
      'header.contact': 'Contact',
      'header.subtitle': 'Researcher & Academic',
      
      // Home Page
      'home.hero.title': 'Welcome to My',
      'home.hero.subtitle': 'Academic Journey',
      'home.hero.description': 'Dedicated researcher and academic professional committed to advancing knowledge through innovative research, scholarly publications, and meaningful contributions to the academic community.',
      'home.viewResearch': 'View Research',
      'home.getInTouch': 'Get in Touch',
      'home.academicExcellence': 'Academic Excellence',
      'home.excellenceDescription': 'Explore my research contributions, publications, and professional journey',
      'home.researchPublications': 'Research Publications',
      'home.yearsExperience': 'Years Experience',
      'home.collaborations': 'Collaborations',
      'home.aboutMe': 'About Me',
      'home.aboutDescription': 'Learn more about my academic background and research interests',
      'home.background': 'Background',
      'home.backgroundDesc': 'Experienced researcher with a strong foundation in academic excellence and a passion for contributing to knowledge advancement.',
      'home.researchFocus': 'Research Focus',
      'home.researchFocusDesc': 'My research interests span multiple disciplines, with a focus on innovative methodologies and practical applications.',
      'home.achievements': 'Achievements',
      'home.achievementsDesc': 'Recognized for academic excellence through various awards, publications, and collaborative projects.',
      'home.learnMore': 'Learn More',
      'home.recentPublications': 'Recent Publications',
      'home.publicationsDescription': 'Latest scholarly contributions and research publications',
      'home.viewAllPublications': 'View All Publications',
      
      // About Page
      'about.title': 'About Me',
      'about.description': 'Learn more about my academic background, research interests, and professional journey',
      'about.academicProfile': 'Academic Profile',
      'about.profileDesc1': 'I am a dedicated researcher and academic professional with a passion for advancing knowledge through innovative research methodologies and collaborative scholarly work. My journey in academia has been driven by curiosity, dedication, and a commitment to making meaningful contributions to my field.',
      'about.profileDesc2': 'Throughout my career, I have focused on developing comprehensive research frameworks that bridge theoretical concepts with practical applications. My work emphasizes interdisciplinary approaches and collaborative partnerships with leading institutions worldwide.',
      'about.profileDesc3': 'I believe in the power of education and research to create positive change in society, and I am committed to mentoring the next generation of researchers and scholars.',
      'about.keyAreas': 'Key Areas',
      'about.background': 'Background',
      'about.backgroundDesc': 'Experienced researcher with a strong foundation in academic excellence and a passion for contributing to knowledge advancement in my field of expertise.',
      'about.researchFocus': 'Research Focus',
      'about.researchFocusDesc': 'My research interests span multiple disciplines, with a focus on innovative methodologies and practical applications that address real-world challenges.',
      'about.achievements': 'Achievements',
      'about.achievementsDesc': 'Recognized for academic excellence and research contributions through various awards, publications, and collaborative projects with leading institutions.',
      'about.valuesPhilosophy': 'Values & Philosophy',
      'about.excellence': 'Excellence',
      'about.excellenceDesc': 'Committed to maintaining the highest standards in research methodology, analysis, and scholarly output.',
      'about.collaboration': 'Collaboration',
      'about.collaborationDesc': 'Believing in the power of collaborative research and interdisciplinary approaches to solve complex problems.',
      'about.innovation': 'Innovation',
      'about.innovationDesc': 'Constantly seeking new perspectives and innovative solutions to advance knowledge and understanding.',
      
      // Research Page
      'research.title': 'Research',
      'research.description': 'Exploring innovative solutions and advancing knowledge across multiple research domains',
      'research.activeAreas': 'Active Research Areas',
      'research.collaborativePartners': 'Collaborative Partners',
      'research.publications': 'Research Publications',
      'research.researchAreas': 'Research Areas',
      'research.primaryResearch': 'Primary Research Area',
      'research.primaryDesc': 'In-depth exploration of core research questions with innovative methodologies and comprehensive analysis.',
      'research.collaborativeStudies': 'Collaborative Studies',
      'research.collaborativeDesc': 'Multi-institutional research projects focusing on interdisciplinary approaches to complex problems.',
      'research.appliedResearch': 'Applied Research',
      'research.appliedDesc': 'Practical applications of theoretical frameworks to address real-world challenges and opportunities.',
      'research.emergingTech': 'Emerging Technologies',
      'research.emergingDesc': 'Investigation of cutting-edge technologies and their potential applications in research contexts.',
      'research.ongoing': 'Ongoing',
      'research.active': 'Active',
      'research.completed': 'Completed',
      'research.planning': 'Planning',
      'research.learnMore': 'Learn More',
      'research.currentProjects': 'Current Projects',
      'research.duration': 'Duration',
      'research.funding': 'Funding',
      'research.collaborators': 'Collaborators',
      'research.project1': 'Advanced Methodological Framework Development',
      'research.project1Desc': 'Developing comprehensive frameworks for advanced research methodologies.',
      'research.project2': 'Cross-Institutional Collaborative Study',
      'research.project2Desc': 'Large-scale collaborative research project with international partners.',
      
      // Publications Page
      'publications.title': 'Publications',
      'publications.description': 'Recent scholarly contributions and research publications',
      'publications.totalPublications': 'Total Publications',
      'publications.citations': 'Citations',
      'publications.hIndex': 'H-Index',
      'publications.authors': 'Authors',
      'publications.publishedIn': 'Published in',
      'publications.journalArticle': 'Journal Article',
      'publications.conferencePaper': 'Conference Paper',
      'publications.reviewArticle': 'Review Article',
      'publications.researchArticle': 'Research Article',
      'publications.perspective': 'Perspective',
      'publications.view': 'View',
      'publications.download': 'Download',
      'publications.stayUpdated': 'Stay Updated',
      'publications.stayUpdatedDesc': 'Get notified about new publications and research updates',
      'publications.subscribe': 'Subscribe to Updates',
      // Publication content translations (EN)
      'publications.title1': 'Advanced Research Methodologies in Contemporary Studies',
      'publications.title2': 'Innovative Approaches to Complex Problem Solving',
      'publications.title3': 'Collaborative Research in the Digital Age',
      'publications.title4': 'Interdisciplinary Frameworks for Modern Research',
      'publications.title5': 'Emerging Trends in Academic Research Methodologies',
      'publications.title6': 'Data-Driven Approaches in Contemporary Studies',
      'publications.abstract1': 'This comprehensive study explores advanced methodologies in contemporary research, providing frameworks for innovative approaches to complex academic challenges.',
      'publications.abstract2': 'Presentation of novel problem-solving methodologies developed through collaborative research initiatives.',
      'publications.abstract3': 'A comprehensive review of collaborative research practices and their evolution in the digital era.',
      'publications.abstract4': 'Development of interdisciplinary frameworks that bridge multiple research domains for comprehensive analysis.',
      'publications.abstract5': 'Analysis of emerging trends and future directions in academic research methodologies.',
      'publications.abstract6': 'Exploration of data-driven methodologies and their applications in contemporary academic research.',
      'publications.statusPublished': 'Published',
      'publications.statusPresented': 'Presented',
      'publications.journal1': 'Journal of Academic Research',
      'publications.journal2': 'International Conference Proceedings',
      'publications.journal3': 'Academic Review Quarterly',
      'publications.journal4': 'Global Research Journal',
      'publications.journal5': 'Future Research Quarterly',
      'publications.journal6': 'Data Science in Academia',
      
      // Work Page
      'work.title': 'Professional Experience',
      'work.description': 'Academic positions and professional roles throughout my career',
      'work.yearsExperience': 'Years Experience',
      'work.institutions': 'Institutions',
      'work.mentees': 'Mentees',
      'work.majorAwards': 'Major Awards',
      'work.workExperience': 'Work Experience',
      'work.seniorResearcher': 'Senior Researcher',
      'work.researchAssociate': 'Research Associate',
      'work.graduateAssistant': 'Graduate Research Assistant',
      'work.juniorResearcher': 'Junior Researcher',
      'work.fullTime': 'Full-time',
      'work.partTime': 'Part-time',
      'work.keyAchievements': 'Key Achievements',
      'work.coreSkills': 'Core Skills',
      'work.awardsRecognition': 'Awards & Recognition',
      
      // Contact Page
      'contact.title': 'Get in Touch',
      'contact.description': 'I\'m always interested in discussing research opportunities, collaborations, and academic partnerships',
      'contact.contactInfo': 'Contact Information',
      'contact.email': 'Email',
      'contact.phone': 'Phone',
      'contact.officeAddress': 'Office Address',
      'contact.officeHours': 'Office Hours',
      'contact.sendEmail': 'Send Email',
      'contact.downloadCV': 'Download CV',
      'contact.sendMessage': 'Send a Message',
      'contact.firstName': 'First Name',
      'contact.lastName': 'Last Name',
      'contact.emailAddress': 'Email Address',
      'contact.institution': 'Institution/Organization',
      'contact.subject': 'Subject',
      'contact.message': 'Message',
      'contact.send': 'Send Message',
      'contact.letsCollaborate': 'Let\'s Collaborate',
      'contact.collaborateDesc': 'I welcome opportunities for research collaboration, academic partnerships, speaking engagements, and consulting projects. Whether you\'re a fellow researcher, student, or industry professional, I\'m always excited to explore new possibilities for meaningful academic and professional connections.',
      'contact.researchCollaboration': 'Research Collaboration',
      'contact.researchCollaborationDesc': 'Joint research projects and academic partnerships',
      'contact.speakingEngagements': 'Speaking Engagements',
      'contact.speakingEngagementsDesc': 'Conference presentations and academic talks',
      'contact.consulting': 'Consulting',
      'contact.consultingDesc': 'Research methodology and academic consulting',
      
      // Footer
      'footer.subtitle': 'Researcher & Academic Professional',
      'footer.copyright': '© 2024 Fantahun Bogale Gereme. All rights reserved.',
      
      // Common
      'common.name': 'Fantahun Bogale Gereme',
    },
    am: {
      // Header
      'header.home': 'ዋና ገጽ',
      'header.about': 'ስለ እኔ',
      'header.research': 'ምርምር',
      'header.publications': 'ፕራብሊኬሽኖች',
      'header.work': 'ስራ',
      'header.contact': 'አድራሻ',
      'header.subtitle': 'ምርምር ሰው እና አካዳሚ',
      
      // Home Page
      'home.hero.title': 'ወደ የእኔ',
      'home.hero.subtitle': 'የአካዳሚ ጉዞ እርስዎን እንደሚያስተውል',
      'home.hero.description': 'የተሰጠ ምርምር ሰው እና አካዳሚ ስራ ሰው እንደሆን በአዳዲስ ምርምር ዘዴዎች፣ በስነ-ጽሑፍ ፕራብሊኬሽኖች እና በአካዳሚ ማህበረሰብ ላይ ትልቅ አስተዋጽዖ በማድረግ እውቀትን ለማሳደግ የተሰጠ።',
      'home.viewResearch': 'ምርምር ይመልከቱ',
      'home.getInTouch': 'አድራሻ ያግኙ',
      'home.academicExcellence': 'የአካዳሚ ስኬት',
      'home.excellenceDescription': 'የእኔን የምርምር አስተዋጽዖዎች፣ ፕራብሊኬሽኖች እና የስራ ስራ ጉዞ ያስሱ',
      'home.researchPublications': 'የምርምር ፕራብሊኬሽኖች',
      'home.yearsExperience': 'የስራ ስራ ዓመታት',
      'home.collaborations': 'ትብብሮች',
      'home.aboutMe': 'ስለ እኔ',
      'home.aboutDescription': 'የእኔን የአካዳሚ ዳራ እና የምርምር ፍላጎቶች ተጨማሪ ይወቁ',
      'home.background': 'ዳራ',
      'home.backgroundDesc': 'የተሰጠ ምርምር ሰው እንደሆን በአካዳሚ ስኬት ላይ ጠንካራ መሰረት እና እውቀትን ለማሳደግ ባለው ቁርጠኝነት።',
      'home.researchFocus': 'የምርምር ያተኩር',
      'home.researchFocusDesc': 'የእኔ የምርምር ፍላጎቶች በብዙ ዘርፎች ላይ ያለው እና በአዳዲስ ዘዴዎች እና በተግባቢ መተግበሪያዎች ላይ ያተኩራል።',
      'home.achievements': 'የተገኙ ስኬቶች',
      'home.achievementsDesc': 'በተለያዩ ሽልማቶች፣ ፕራብሊኬሽኖች እና ትብብር ፕሮጀክቶች ላይ በአካዳሚ ስኬት የተገኘ።',
      'home.learnMore': 'ተጨማሪ ይወቁ',
      'home.recentPublications': 'የቅርብ ጊዜ ፕራብሊኬሽኖች',
      'home.publicationsDescription': 'የቅርብ ጊዜ የተደረጉ ስነ-ጽሑፍ አስተዋጽዖዎች እና የምርምር ፕራብሊኬሽኖች',
      'home.viewAllPublications': 'ሁሉንም ፕራብሊኬሽኖች ይመልከቱ',
      
      // About Page
      'about.title': 'ስለ እኔ',
      'about.description': 'የእኔን የአካዳሚ ዳራ፣ የምርምር ፍላጎቶች እና የስራ ስራ ጉዞ ተጨማሪ ይወቁ',
      'about.academicProfile': 'የአካዳሚ መገለጫ',
      'about.profileDesc1': 'እኔ የተሰጠ ምርምር ሰው እና አካዳሚ ስራ ሰው እንደሆን በአዳዲስ ምርምር ዘዴዎች እና በትብብር ስነ-ጽሑፍ ስራ ላይ እውቀትን ለማሳደግ ባለው ቁርጠኝነት እንደሆን። የእኔ በአካዳሚ ስራ ላይ ያለው ጉዞ በጥያቄ፣ በቁርጠኝነት እና በማህበረሰቤ ላይ ትልቅ አስተዋጽዖ በማድረግ የተሰጠ።',
      'about.profileDesc2': 'በስራ ስራዬ ሁሉ በንድፈ ሀሳብ ግንኙነቶች እና ተግባቢ መተግበሪያዎች መካከል ያለውን ክፍተት የሚያስገኝ ሁለገብ የምርምር መዋቅሮች ለመዘጋጀት ያተኩራለሁ። የእኔ ስራ በዘርፎች መካከል ያለውን አመለካከት እና በዓለም አቀፍ መስሪያ ቤቶች ላይ ባለው ትብብር አጥንተኛ ነው።',
      'about.profileDesc3': 'በትምህርት እና በምርምር ላይ በማህበረሰብ ላይ አዎንታዊ ለውጥ ለመፍጠር ያለውን ኃይል እያምን ነው፣ እና የሚቀጥለውን የምርምር ሰዎች እና ስነ-ጽሑፍ ሰዎች ለመምራት ቁርጠኝ ነኝ።',
      'about.keyAreas': 'ዋና ዋና መስኮች',
      'about.background': 'ዳራ',
      'about.backgroundDesc': 'የተሰጠ ምርምር ሰው እንደሆን በአካዳሚ ስኬት ላይ ጠንካራ መሰረት እና በስራ ስራዬ ላይ እውቀትን ለማሳደግ ባለው ቁርጠኝነት።',
      'about.researchFocus': 'የምርምር ያተኩር',
      'about.researchFocusDesc': 'የእኔ የምርምር ፍላጎቶች በብዙ ዘርፎች ላይ ያለው እና በአዳዲስ ዘዴዎች እና በተግባቢ መተግበሪያዎች ላይ ያተኩራል እንደሆን በእውነተኛ ዓለም ላይ ያለውን ተግምጋሚ ለመፍታት።',
      'about.achievements': 'የተገኙ ስኬቶች',
      'about.achievementsDesc': 'በአካዳሚ ስኬት እና በምርምር አስተዋጽዖዎች ላይ በተለያዩ ሽልማቶች፣ ፕራብሊኬሽኖች እና በአካዳሚ መስሪያ ቤቶች ላይ ባለው ትብብር ፕሮጀክቶች የተገኘ።',
      'about.valuesPhilosophy': 'እሴቶች እና ፍልስፍና',
      'about.excellence': 'ስኬት',
      'about.excellenceDesc': 'በምርምር ዘዴ፣ በመተንተን እና በስነ-ጽሑፍ ስራ ላይ ከፍተኛ ደረጃዎችን ለመጠበቅ ቁርጠኝ።',
      'about.collaboration': 'ትብብር',
      'about.collaborationDesc': 'በትብብር ምርምር እና በዘርፎች መካከል ያለውን አመለካከት ለተወሳሰቡ ችግሮች ለመፍታት ባለው ኃይል እያምን።',
      'about.innovation': 'አዳዲስ ነገሮች',
      'about.innovationDesc': 'እውቀትን እና መረዳትን ለማሳደግ አዳዲስ አመለካከቶች እና አዳዲስ መፍትሄዎች ለመፈለግ ያለማቋረጥ።',
      
      // Research Page
      'research.title': 'ምርምር',
      'research.description': 'አዳዲስ መፍትሄዎችን ለመፈለግ እና በብዙ የምርምር መስኮች ላይ እውቀትን ለማሳደግ እያሰራሁ',
      'research.activeAreas': 'ንቁ የምርምር መስኮች',
      'research.collaborativePartners': 'ትብብር አጋሮች',
      'research.publications': 'የምርምር ፕራብሊኬሽኖች',
      'research.researchAreas': 'የምርምር መስኮች',
      'research.primaryResearch': 'ዋና የምርምር መስኮት',
      'research.primaryDesc': 'በአዳዲስ ዘዴዎች እና በሁለገብ መተንተን የተሰጠ የዋና ዋና የምርምር ጥያቄዎች ጥልቀት ያለው ምርምር።',
      'research.collaborativeStudies': 'ትብብር ምርምር',
      'research.collaborativeDesc': 'በተወሳሰቡ ችግሮች ላይ በዘርፎች መካከል ያለውን አመለካከት የሚያተኩሩ በብዙ መስሪያ ቤቶች ላይ የሚደረጉ የምርምር ፕሮጀክቶች።',
      'research.appliedResearch': 'የተግባቢ ምርምር',
      'research.appliedDesc': 'በእውነተኛ ዓለም ላይ ያለውን ተግምጋሚ እና እድሎችን ለመፍታት የንድፈ ሀሳብ መዋቅሮች ተግባቢ መተግበሪያዎች።',
      'research.emergingTech': 'አዳዲስ ቴክኖሎጂዎች',
      'research.emergingDesc': 'በምርምር አውድ ላይ የአዳዲስ ቴክኖሎጂዎች እና የእነሱ ተግባቢ መተግበሪያዎች ምርምር።',
      'research.ongoing': 'በሂደት ላይ',
      'research.active': 'ንቁ',
      'research.completed': 'የተጠናቀቀ',
      'research.planning': 'በዕቅድ ላይ',
      'research.learnMore': 'ተጨማሪ ይወቁ',
      'research.currentProjects': 'የአሁን ፕሮጀክቶች',
      'research.duration': 'ጊዜ',
      'research.funding': 'ገንዘብ',
      'research.collaborators': 'ትብብር አጋሮች',
      'research.project1': 'የአዳዲስ ዘዴዎች መዋቅር ማሳደጊያ',
      'research.project1Desc': 'ለአዳዲስ የምርምር ዘዴዎች ሁለገብ መዋቅሮች ማሳደጊያ።',
      'research.project2': 'በመስሪያ ቤቶች መካከል ያለው ትብብር ምርምር',
      'research.project2Desc': 'ከዓለም አቀፍ አጋሮች ጋር ትልልቅ የትብብር ምርምር ፕሮጀክቶች።',
      
      // Publications Page
      'publications.title': 'ፕራብሊኬሽኖች',
      'publications.description': 'የቅርብ ጊዜ የተደረጉ ስነ-ጽሑፍ አስተዋጽዖዎች እና የምርምር ፕራብሊኬሽኖች',
      'publications.totalPublications': 'ጠቅላላ ፕራብሊኬሽኖች',
      'publications.citations': 'ዋቢዎች',
      'publications.hIndex': 'H-መረጃ',
      'publications.authors': 'ደራሲዎች',
      'publications.publishedIn': 'የተታተመበት',
      'publications.journalArticle': 'የጽሑፍ ጽሑፍ',
      'publications.conferencePaper': 'የወጥመድ ጽሑፍ',
      'publications.reviewArticle': 'የግምገማ ጽሑፍ',
      'publications.researchArticle': 'የምርምር ጽሑፍ',
      'publications.perspective': 'አመለካከት',
      'publications.view': 'ይመልከቱ',
      'publications.download': 'ያውርዱ',
      'publications.stayUpdated': 'ወቅታዊ ይሁኑ',
      'publications.stayUpdatedDesc': 'ስለ አዳዲስ ፕራብሊኬሽኖች እና የምርምር ዝመናዎች ማሳወቂያ ያግኙ',
      'publications.subscribe': 'ወቅታዊ ለመሆን ይመዝገቡ',
      // Publication content translations
      'publications.title1': 'የአዳዲስ ዘዴዎች በዘመናዊ ምርምር ላይ',
      'publications.title2': 'የተወሳሰቡ ችግሮች ለመፍታት አዳዲስ አመለካከቶች',
      'publications.title3': 'በዲጂታል ዘመን ውስጥ ያለው ትብብር ምርምር',
      'publications.title4': 'የዘመናዊ ምርምር ለዘርፎች መካከል ያለው መዋቅር',
      'publications.title5': 'የአካዳሚ ምርምር ዘዴዎች ውስጥ ያሉ አዳዲስ አዝማሚያዎች',
      'publications.title6': 'የውሂብ የተመሰረቱ አመለካከቶች በዘመናዊ ምርምር ላይ',
      'publications.abstract1': 'ይህ ሁለገብ ምርምር በዘመናዊ ምርምር ላይ ያሉ አዳዲስ ዘዴዎችን ያስራል፣ የተወሳሰቡ የአካዳሚ ተግምጋሚዎችን ለመፍታት አዳዲስ አመለካከቶችን የሚያቀርብ መዋቅሮችን ያቀርባል።',
      'publications.abstract2': 'ከትብብር ምርምር ተነሳሽነቶች የተወጡ አዳዲስ የችግር መፍቻ ዘዴዎች የተሰጡ።',
      'publications.abstract3': 'በዲጂታል ዘመን ውስጥ የትብብር ምርምር ስራዎች እና የእነሱ እድገት ላይ የተሰጠ ሁለገብ ግምገማ።',
      'publications.abstract4': 'ብዙ የምርምር መስኮችን ለሁለገብ መተንተን የሚያገኙ የዘርፎች መካከል ያለው መዋቅር ማሳደጊያ።',
      'publications.abstract5': 'የአካዳሚ ምርምር ዘዴዎች ውስጥ ያሉ አዳዲስ አዝማሚያዎች እና የወደፊት አቅጣጫዎች መተንተን።',
      'publications.abstract6': 'የውሂብ የተመሰረቱ ዘዴዎች እና በዘመናዊ አካዳሚ ምርምር ላይ ያሉ መተግበሪያዎቻቸው ምርምር።',
      'publications.statusPublished': 'የተታተመ',
      'publications.statusPresented': 'የተቀረበ',
      'publications.journal1': 'የአካዳሚ ምርምር ጽሑፍ',
      'publications.journal2': 'የዓለም አቀፍ ወጥመድ ሂደቶች',
      'publications.journal3': 'የአካዳሚ ግምገማ ሩብ ዓመት',
      'publications.journal4': 'የዓለም አቀፍ ምርምር ጽሑፍ',
      'publications.journal5': 'የወደፊት ምርምር ሩብ ዓመት',
      'publications.journal6': 'የውሂብ ሳይንስ በአካዳሚ ላይ',
      
      // Work Page
      'work.title': 'የስራ ስራ ልምድ',
      'work.description': 'በስራ ስራዬ ሁሉ የአካዳሚ ድርሻዎች እና የስራ ስራ ሚናዎች',
      'work.yearsExperience': 'የስራ ስራ ዓመታት',
      'work.institutions': 'መስሪያ ቤቶች',
      'work.mentees': 'የተምሩ ሰዎች',
      'work.majorAwards': 'ዋና ዋና ሽልማቶች',
      'work.workExperience': 'የስራ ስራ ልምድ',
      'work.seniorResearcher': 'የመሪ ምርምር ሰው',
      'work.researchAssociate': 'የምርምር አጋር',
      'work.graduateAssistant': 'የመጀመሪያ ዲግሪ የምርምር አጋር',
      'work.juniorResearcher': 'የመጀመሪያ ደረጃ ምርምር ሰው',
      'work.fullTime': 'ሙሉ ጊዜ',
      'work.partTime': 'ከፊል ጊዜ',
      'work.keyAchievements': 'ዋና ዋና የተገኙ ስኬቶች',
      'work.coreSkills': 'ዋና ዋና ክህሎቶች',
      'work.awardsRecognition': 'ሽልማቶች እና እውቅና',
      // Work content translations
      'work.institution1': 'የአዳዲስ ምርምር መስክ',
      'work.institution2': 'የዓለም አቀፍ ምርምር ማዕከል',
      'work.institution3': 'የግዛት ዩኒቨርሲቲ',
      'work.institution4': 'የክልል ምርምር ላቦራቶሪ',
      'work.location1': 'የአካዳሚ ከተማ',
      'work.location2': 'የዓለም አቀፍ ዩኒቨርሲቲ',
      'work.location3': 'የዩኒቨርሲቲ ከተማ',
      'work.location4': 'የምርምር ፓርክ',
      'work.description1': 'የአዳዲስ ዘዴዎች ምርምር ተነሳሽነቶችን እና የመጀመሪያ ደረጃ ምርምር ሰዎችን በአዳዲስ ዘዴዎች ለመምራት የሚያስተምሩ። ብዙ የምርምር ፕሮጀክቶችን ለመምራት እና የዓለም አቀፍ ትብብሮችን ለማስተባበር ተጠያቂ።',
      'work.description2': 'በብዙ መስሪያ ቤቶች ላይ ባለው ፕሮጀክት ላይ ገለልተኛ ምርምር እና ትብብር ሰራ። አዳዲስ የምርምር ዘዴዎችን አዳብረ እና በገንዘብ ማግኛ ላይ አስተዋጽዖ አደረገ።',
      'work.description3': 'የመጀመሪያ ዲግሪ መስፈለጊያዎችን እያሟላ የአካዳሚ ምርምርን ድገፈ። ውሂብ ማሰተሳሰር፣ መተንተን እና የጽሑፍ አዘጋጅ ስራ ላይ አገለገለ።',
      'work.description4': 'የመጀመሪያ ደረጃ የምርምር ድርሻ ውሂብ ማሰተሳሰር እና የመጀመሪያ መተንተን ላይ ያተኩራል። በምርምር ዘዴዎች እና በአካዳሚ ጽሑፍ ላይ መሰረታዊ ልምድ አገኘ።',
      'work.achievement1': 'ከዓለም አቀፍ አጋሮች ጋር 5 ዋና ዋና የምርምር ፕሮጀክቶችን መምራት',
      'work.achievement2': '12 የመጀመሪያ ዲግሪ ተማሪዎችን እና የመጀመሪያ ደረጃ ምርምር ሰዎችን መምራት',
      'work.achievement3': '$500K የምርምር ገንዘብ ማግኛ',
      'work.achievement4': '8 የተገምገሙ ጽሑፎች ማተም',
      'work.achievement5': '3 የተሳካሩ የገንዘብ ማግኛ ላይ አስተዋጽዖ',
      'work.achievement6': '6 የምርምር ጽሑፎች በከፍተኛ ደረጃ ጽሑፎች ላይ ማተም',
      'work.achievement7': '8 የዓለም አቀፍ ወጥመዶች ላይ ያቀረብ',
      'work.achievement8': 'ከ5 አገሮች ምርምር ሰዎች ጋር ትብብር',
      'work.achievement9': 'የPhD ዲሰርቴሽን በተሻለ ሁኔታ ማጠናቀቅ',
      'work.achievement10': '4 የምርምር ፕራብሊኬሽኖች በትብብር ማተም',
      'work.achievement11': 'የመጀመሪያ ዲግሪ ምርምር ስኬት ሽልማት ማግኛ',
      'work.achievement12': 'የመጀመሪያ ዲግሪ ኮርሶች እንደ የመምራት አጋር መምራት',
      'work.achievement13': '2 ዋና ዋና የምርምር ምርምር ላይ አስተዋጽዖ',
      'work.achievement14': 'የስታቲስቲክስ መተንተኛ ሶፍትዌር ላይ ችሎት ማግኛ',
      'work.achievement15': 'የክልል ወጥመዶች ላይ ያገኙ ውጤቶች ማቅረብ',
      'work.achievement16': 'የአዳዲስ የምርምር ዘዴ ስልጠና ማጠናቀቅ',
      'work.skill1': 'የምርምር ዘዴ',
      'work.skill2': 'የስታቲስቲክስ መተንተኛ',
      'work.skill3': 'የውሂብ ማሳያ',
      'work.skill4': 'የገንዘብ ማግኛ ጽሑፍ',
      'work.skill5': 'የፕሮጀክት አስተዳደር',
      'work.skill6': 'የአካዳሚ ጽሑፍ',
      'work.skill7': 'የጥምረት ግምገማ',
      'work.skill8': 'የዓለም አቀፍ ትብብር',
      'work.skill9': 'መምራት',
      'work.skill10': 'የወጥመድ ማቅረብ',
      'work.award1': 'የምርምር ዘዴ ላይ ያለው ስኬት ሽልማት',
      'work.award2': 'የተሻለ ጽሑፍ ሽልማት',
      'work.award3': 'የወጣት ምርምር ሰው ገንዘብ ማግኛ',
      'work.organization1': 'የአካዳሚ ምርምር ማህበር',
      'work.organization2': 'የዓለም አቀፍ ምርምር ወጥመድ',
      'work.organization3': 'የብሔራዊ ምርምር መሰረት',
      'work.awardDesc1': 'በምርምር ዘዴ ላይ ያለው አስተማማሪ አስተዋጽዖ ላይ የተገኘ እውቅና',
      'work.awardDesc2': 'በትብብር ዘዴዎች ላይ ያለው አዳዲስ ምርምር ላይ የተሰጠ',
      'work.awardDesc3': 'ለወጣት ምርምር ሰዎች የተዘጋጀ ውድድር ገንዘብ ማግኛ',
      
      // Contact Page
      'contact.title': 'አድራሻ ያግኙ',
      'contact.description': 'ስለ ምርምር እድሎች፣ ትብብሮች እና የአካዳሚ ትብብሮች ለመወያየት ሁልጊዜ ፈቃደኛ ነኝ',
      'contact.contactInfo': 'የመገናኛ መረጃ',
      'contact.email': 'ኢሜይል',
      'contact.phone': 'ስልክ',
      'contact.officeAddress': 'የቢሮ አድራሻ',
      'contact.officeHours': 'የቢሮ ሰዓቶች',
      'contact.sendEmail': 'ኢሜይል ይላኩ',
      'contact.downloadCV': 'CV ያውርዱ',
      'contact.sendMessage': 'መልእክት ይላኩ',
      'contact.firstName': 'የመጀመሪያ ስም',
      'contact.lastName': 'የመጨረሻ ስም',
      'contact.emailAddress': 'የኢሜይል አድራሻ',
      'contact.institution': 'መስሪያ ቤት/ድርጅት',
      'contact.subject': 'ርዕስ',
      'contact.message': 'መልእክት',
      'contact.send': 'መልእክት ይላኩ',
      'contact.letsCollaborate': 'እንድንተባብር እንድንሰራ',
      'contact.collaborateDesc': 'ለምርምር ትብብር፣ ለአካዳሚ ትብብሮች፣ ለመደረጊያ ንግግሮች እና ለመኮንሰሊንግ ፕሮጀክቶች እድሎችን እወቃለሁ። የምርምር ሰው፣ ተማሪ ወይም የኢንዱስትሪ ስራ ሰው ለመሆን ያለው ሰው ለሆን አዳዲስ እድሎችን ለመፈለግ ሁልጊዜ ተስማምቻለሁ።',
      'contact.researchCollaboration': 'የምርምር ትብብር',
      'contact.researchCollaborationDesc': 'የትብብር ምርምር ፕሮጀክቶች እና የአካዳሚ ትብብሮች',
      'contact.speakingEngagements': 'የመደረጊያ ንግግሮች',
      'contact.speakingEngagementsDesc': 'የወጥመድ አቀራረቦች እና የአካዳሚ ንግግሮች',
      'contact.consulting': 'መኮንሰሊንግ',
      'contact.consultingDesc': 'የምርምር ዘዴ እና የአካዳሚ መኮንሰሊንግ',
      
      // Footer
      'footer.subtitle': 'ምርምር ሰው እና የአካዳሚ ስራ ሰው',
      'footer.copyright': '© 2024 ፋንታሁን ቦጋሌ ገረመ። ሁሉም መብቶች የተጠበቁ ናቸው።',
      
      // Common
      'common.name': 'ፋንታሁን ቦጋለ ገረመ',
    }
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
} 